sudo: required

language: python

services:
  - docker

before_install:
  - docker pull zookeeper
  - docker run -p 127.0.0.1:2181:2181 -d zookeeper
  
python:
    - "2.7"

install:
  - pip install kazoo
  - pip install pytest
  
script:
  - py.test -v -l

after_success:
  - python ansibleKeeper.py -h
  